service: calculate
provider:
  name: aws
  runtime: dart
  lambdaHashingVersion: 20201221
  memorySize: 128
  region: eu-west-1

package:
  individually: true

plugins:
  - serverless-dart

functions:
  postRequest:
    handler: calculate.addOnePost
    events:
      - http:
          path: /add-one-post
          method: POST
          cors: true
  getRequestPath:
    handler: calculate.addOnePath
    events:
      - http:
          path: /add-one-path/{value}
          method: GET
          cors: true
  getRequestQuery:
    handler: calculate.addOneQuery
    events:
      - http:
          path: /add-one
          method: GET
          cors: true
